#ファイル名 Chapter11/listing11-15.py
f = open('somefile4.txt', 'w')
print('First', 'line', file=f)
print('Second', 'line', file=f)
print('Third', 'line', file=f)
print('最後の行:', 'おまけです', file=f)
f.close()
lines = list(open('somefile4.txt'))
print(lines)
first, second, third, fourth = open('somefile4.txt')
print(first)
print(second)
print(third)
print(fourth)
